# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8995b0e5a2b889a90fb50e9e500d1ca36d22786d768c5c8dacc4718f12eddab9521aa79fba25fa13111d2f0ae2754747b03f65231fdf2fb29079124b936d8f5

test:
  secret_key_base: 27c5c0f88ace3c29c57b932886c5f5d2f5f62b3e285f3095a7df865259a573b6b63284b3a04d523ea2e111980d228ae29f836f04657b518f69526f99f258f31a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
